import './globals.css'
import Chakra from './components/Chakra'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Chakra>
          {children}
        </Chakra>
      </body>
    </html>
  )
}
