import './globals.css'

import Chakra from './components/Chakra'
import QueryClientProv from './components/QueryClientProv'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <QueryClientProv>
          <Chakra>
            {children}
          </Chakra>
        </QueryClientProv>
      </body>
    </html>
  )
}
